/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labtwo;



import data.user;
import javax.swing.JOptionPane;

/**
 *
 * @author jeyarajjeyakumar
 */
public class mainjframe extends javax.swing.JFrame {

    

    /**
     * Creates new form mainjframe
     */
    user inputuser;
    
    /**
     *
     */
    public mainjframe () {
        initComponents();
        inputuser = new user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitpane = new javax.swing.JSplitPane();
        toppanel = new javax.swing.JPanel();
        viewbutton = new javax.swing.JButton();
        bottompanel = new javax.swing.JPanel();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        telephonenumberlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        countrylabel = new javax.swing.JLabel();
        majorlabel = new javax.swing.JLabel();
        firstnamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        telephonenumberfield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        countryfield = new javax.swing.JTextField();
        majorfield = new javax.swing.JTextField();
        titlelabel = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        photolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitpane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        viewbutton.setText("View Details");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });

        firstnamelabel.setText("First Name");

        lastnamelabel.setText("Last Name");

        agelabel.setText("Age");

        telephonenumberlabel.setText("Telephone number");

        emaillabel.setText("Email");

        addresslabel.setText("Address");

        citylabel.setText("City");

        countrylabel.setText("Country");

        majorlabel.setText("Major");

        countryfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryfieldActionPerformed(evt);
            }
        });

        titlelabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("Enter User Details");

        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        photolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labtwo/dreamstime_xxl_65780868_small.jpg"))); // NOI18N

        javax.swing.GroupLayout bottompanelLayout = new javax.swing.GroupLayout(bottompanel);
        bottompanel.setLayout(bottompanelLayout);
        bottompanelLayout.setHorizontalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottompanelLayout.createSequentialGroup()
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottompanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countrylabel)
                            .addComponent(majorlabel)
                            .addGroup(bottompanelLayout.createSequentialGroup()
                                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnamelabel)
                                    .addComponent(lastnamelabel)
                                    .addComponent(agelabel)
                                    .addComponent(telephonenumberlabel)
                                    .addComponent(emaillabel)
                                    .addComponent(addresslabel)
                                    .addComponent(citylabel))
                                .addGap(63, 63, 63)
                                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(agefield)
                                    .addComponent(telephonenumberfield)
                                    .addComponent(emailfield)
                                    .addComponent(addressfield)
                                    .addComponent(cityfield)
                                    .addComponent(firstnamefield))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(photolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bottompanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(bottompanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bottompanelLayout.createSequentialGroup()
                            .addGap(275, 275, 275)
                            .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(majorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(countryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        bottompanelLayout.setVerticalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottompanelLayout.createSequentialGroup()
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottompanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnamelabel)
                            .addComponent(firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnamelabel)
                            .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agelabel)
                            .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephonenumberlabel)
                            .addComponent(telephonenumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bottompanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(photolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillabel)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citylabel)
                    .addComponent(cityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(countrylabel)
                    .addComponent(countryfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(majorlabel)
                    .addComponent(majorfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(savebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bottompanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addComponent(viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottompanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        splitpane.setLeftComponent(toppanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitpane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        user inputuser = new user();
        inputuser.setFirstname(firstnamefield.getText());
        inputuser.setLastname(lastnamefield.getText());
        inputuser.setAge(agefield.getText());
        inputuser.setTelephonenumber(telephonenumberfield.getText());
        inputuser.setEmail(emailfield.getText());
        inputuser.setAddress(addressfield.getText());
        inputuser.setCity(cityfield.getText());
        inputuser.setCountry(countryfield.getText());
        inputuser.setMajor(majorfield.getText());
        
        JOptionPane.showMessageDialog(this, "User saved successfully", "Success", HEIGHT);
    
        
    }//GEN-LAST:event_savebuttonActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed
        //boolean inputuser;
        // TODO add your handling code here:
        //pass user object and switch to a different panel to view data
        if (inputuser.getFirstname() == null || inputuser.getLastname() == null || inputuser.getAge() == null || inputuser.getTelephonenumber() == null || inputuser.getEmail() == null || inputuser.getAddress() == null || inputuser.getCity() == null || inputuser.getCountry() == null || inputuser.getMajor() == null) {    
            JOptionPane.showMessageDialog(this, "Please enter user details", "Error", HEIGHT);
        } 
        else {
            // pass data to newly created panel and switch to that panel
            viewdetailspanel viewPanel = new viewdetailspanel(inputuser); // creation new panel
            splitpane.setBottomComponent(viewbutton); // telling splitPanel to switch
            
        }
    

    }//GEN-LAST:event_viewbuttonActionPerformed

    private void countryfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()  {
            public void run(){
            new mainjframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField agefield;
    private javax.swing.JLabel agelabel;
    private javax.swing.JPanel bottompanel;
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel citylabel;
    private javax.swing.JTextField countryfield;
    private javax.swing.JLabel countrylabel;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField majorfield;
    private javax.swing.JLabel majorlabel;
    private javax.swing.JLabel photolabel;
    private javax.swing.JButton savebutton;
    private javax.swing.JSplitPane splitpane;
    private javax.swing.JTextField telephonenumberfield;
    private javax.swing.JLabel telephonenumberlabel;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JPanel toppanel;
    private javax.swing.JButton viewbutton;
    // End of variables declaration//GEN-END:variables
}
