/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package labtwo;

import data.user;

/**
 *
 * @author jeyarajjeyakumar
 */
public class viewdetailspanel extends javax.swing.JPanel {

    /**
     * Creates new form viewdetailspanel
     */
    user inputuser;
    
    public viewdetailspanel(user givenuser) {
        initComponents();
        this.inputuser = givenuser;
        populatefields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelabel = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        telephonenumberlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        countrylabel = new javax.swing.JLabel();
        majorlabel = new javax.swing.JLabel();
        firstnameanswer = new javax.swing.JLabel();
        lastnameanswer = new javax.swing.JLabel();
        ageanswer = new javax.swing.JLabel();
        telephonenumberanswer = new javax.swing.JLabel();
        emailanswer = new javax.swing.JLabel();
        addressanswer = new javax.swing.JLabel();
        cityanswer = new javax.swing.JLabel();
        countryanswer = new javax.swing.JLabel();
        majoranswer = new javax.swing.JLabel();

        titlelabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("The Given User Details");

        firstnamelabel.setText("First Name");

        lastnamelabel.setText("Last Name");

        agelabel.setText("Age");

        telephonenumberlabel.setText("Telephone number");

        emaillabel.setText("Email");

        addresslabel.setText("Address");

        citylabel.setText("City");

        countrylabel.setText("Country");

        majorlabel.setText("Major");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(firstnamelabel)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstnameanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ageanswer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(lastnameanswer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(telephonenumberanswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailanswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressanswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cityanswer, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(majoranswer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(countryanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastnamelabel)
                        .addComponent(agelabel)
                        .addComponent(telephonenumberlabel)
                        .addComponent(emaillabel)
                        .addComponent(addresslabel)
                        .addComponent(citylabel)
                        .addComponent(countrylabel)
                        .addComponent(majorlabel)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(firstnameanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastnameanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ageanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(telephonenumberanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addressanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cityanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(countryanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(majoranswer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(89, 89, 89)
                    .addComponent(lastnamelabel)
                    .addGap(23, 23, 23)
                    .addComponent(agelabel)
                    .addGap(27, 27, 27)
                    .addComponent(telephonenumberlabel)
                    .addGap(22, 22, 22)
                    .addComponent(emaillabel)
                    .addGap(18, 18, 18)
                    .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(citylabel)
                    .addGap(18, 18, 18)
                    .addComponent(countrylabel)
                    .addGap(15, 15, 15)
                    .addComponent(majorlabel)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressanswer;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel ageanswer;
    private javax.swing.JLabel agelabel;
    private javax.swing.JLabel cityanswer;
    private javax.swing.JLabel citylabel;
    private javax.swing.JLabel countryanswer;
    private javax.swing.JLabel countrylabel;
    private javax.swing.JLabel emailanswer;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel firstnameanswer;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JLabel lastnameanswer;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel majoranswer;
    private javax.swing.JLabel majorlabel;
    private javax.swing.JLabel telephonenumberanswer;
    private javax.swing.JLabel telephonenumberlabel;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables

    private void populatefields() {
        //take data from the user object set it to the fields
        firstnameanswer.setText(inputuser.getFirstname());
        lastnameanswer.setText(inputuser.getLastname());
        ageanswer.setText(inputuser.getAge());
        telephonenumberanswer.setText(inputuser.getTelephonenumber());
        emailanswer.setText(inputuser.getEmail());
        addressanswer.setText(inputuser.getAddress());
        cityanswer.setText(inputuser.getCity());
        countryanswer.setText(inputuser.getCountry());
        majoranswer.setText(inputuser.getMajor());
    }
}
